name: "🐞 Bug Report"
description: Report a technical or gameplay bug affecting the Horicraft server.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Please fill out the details below to help us resolve the issue quickly.
  - type: input
    id: summary
    attributes:
      label: "Short Summary"
      description: Briefly describe the bug.
      placeholder: "Example: Cannot open chests in my base"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or Videos"
      description: Attach any relevant screenshots or videos.
    validations:
      required: false
  - type: input
    id: minecraft-username
    attributes:
      label: "Your Minecraft Username"
      description: Helps us identify you in-game.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
