name: "🚩 Player Report"
description: Report a player for breaking rules or inappropriate behavior.
labels: [player report]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚩 Player Report

        Please provide as much detail as possible.
  - type: input
    id: reported-player
    attributes:
      label: "Player Username"
      description: The username of the player you are reporting.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "Reason for Report"
      description: Describe what happened and why you are reporting this player.
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: "Evidence"
      description: Attach screenshots, chat logs, or other evidence.
    validations:
      required: false
  - type: input
    id: your-username
    attributes:
      label: "Your Minecraft Username"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: "Type of Incident"
      options:
        - Harassment
        - Cheating/Hacking
        - Inappropriate Language
        - Other
    validations:
      required: true
