name: "❓ Question"
description: Ask a general question or request clarification.
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        ## ❓ Question

        Ask your question below and a staff member will respond as soon as possible.
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: What would you like to know?
    validations:
      required: true
  - type: input
    id: your-username
    attributes:
      label: "Your Minecraft Username"
    validations:
      required: false
